export const FETCH_POKEMONS = 'FETCH_POKEMONS'
export const FETCHING_POKEMONS = 'FETCHING_POKEMONS'
export const FETCH_ERROR_POKEMONS = 'FETCH_ERROR_POKEMONS'

export const FETCH_POKEMON = 'FETCH_POKEMON'
export const FETCHING_POKEMON = 'FETCHING_POKEMON'
export const FETCH_ERROR_POKEMON = 'FETCH_ERROR_POKEMON'

export const FETCH_SOMETHING = 'FETCH_SOMETHING'
export const FETCHING_SOMETHING = 'FETCHING_SOMETHING'
export const FETCH_ERROR_SOMETHING = 'FETCH_ERROR_SOMETHING'
