import { RootState } from '@/redux/rootReducer';
import Head from 'next/head';
import React from 'react';
import { connect } from 'react-redux';
import { getPokemons } from '@/redux/base/actions/pokemons';
import 'animate.css';
import Link from 'next/link';
import Layout from '../components/layout';

const mapStateToProps = (state: RootState) => {
  return {
  }
}
const mapDispatchToProps = {
  
}
export type HomePropTypes = {
  
}

const Home = () =>  {

  return (
    <>
      <Head>
        <title>Base Next 13 App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={`d-flex justify-content-center align-items-center h-100`}>
          <img src="/imgPrincipal.png" alt="" className='h-100 animate__animated animate__fadeInLeft' />
          <Link href="/pokemons" type="button" className="btn btn-outline-warning btn-lg animate__animated animate__tada" >
            Obtener Pokemons
          </Link>
        </div>  
      </Layout>
    </>
  )
}
export default connect(mapStateToProps, mapDispatchToProps)(Home)