import { BaseReducerPropsType, ServerStatus } from '@/models/globalModels';
import { RootState } from '@/redux/rootReducer';
import Head from 'next/head';
import React from 'react';
import { connect } from 'react-redux';
import { testCall } from '@/redux/base/actions';

const mapStateToProps = (state: RootState) => {
  return {
    baseState: state.base
  }
}
const mapDispatchToProps = {
  testCall
}
export type HomePropTypes = {
  baseState: BaseReducerPropsType,
  testCall: Function
}

const Home = ({baseState, testCall}: HomePropTypes) =>  {

  React.useEffect(() => {
    console.log("baseState",baseState)
  },[baseState.somethingStatus])

  React.useEffect(() => {
    testCall()
  },[])

  return (
    <>
      <Head>
        <title>Base Next 13 App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container`}>
        <div className={`row mt-4`}>
          <div className={`col-6`}>
            <p>Something!</p>
            <p>Here goes the first version</p>
          </div>
          <div className={`col-6`}>
            <p>{ServerStatus[baseState.somethingStatus]}</p>
          </div>
        </div>

      </main>
    </>
  )
}
export default connect(mapStateToProps, mapDispatchToProps)(Home)